services:

  db:
    image: postgres:16-alpine
    container_name: ecommerce_db
    restart: unless-stopped
    environment:
      POSTGRES_DB:       ${DB_DATABASE}
      POSTGRES_USER:     ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"   # solo localhost del VPS
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - app_storage:/var/www/html/storage/app
      - app_logs:/var/www/html/storage/logs
    ports:
      - "8090:8080" # Puerto expuesto en el servidor (8090) -> Reverb en Docker (8080)
    networks:
      - backend
      - npm_network   # red de NPM para que hable directo al contenedor

networks:
  backend:
    driver: bridge
  npm_network:
    external: true
    name: nginx-proxy-manager_default

volumes:
  db_data:
  app_storage:
  app_logs:
